---
name: 'Allocate Traffic'
description: 'A composite action to allocate traffic for an Azure Machine Learning online endpoint'
inputs:
  endpoint_name:
    description: 'Name of the Azure Machine Learning online endpoint'
    type: string
    required: true
  resource_group:
    description: 'Name of the Azure resource group'
    type: string
    required: true
  workspace_name:
    description: 'Name of the Azure Machine Learning workspace'
    type: string
    required: true
  traffic_allocation:
    description: 'Traffic allocation for the Azure Machine Learning online endpoint'
    type: string
    required: true
  deploy_name:
    description: 'Name of the Azure Machine Learning deployment'
    type: string
    required: true
  azure_tenant_id:
    description: 'Azure tenant ID'
    type: string
    required: true
  azure_client_id:
    description: 'User Assigned - client ID'
    type: string
    required: true
  azure_subscription:
    description: 'Azure subscription ID'
    type: string
    required: true
  audience:
    description: 'Audience for the Azure Machine Learning online endpoint'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Az CLI login
      uses: azure/login@v1
      with:
          tenant-id: ${{ inputs.azure_tenant_id }}
          client-id: ${{ inputs.azure_client_id }}
          subscription-id: ${{ inputs.azure_subscription }}
          audience: ${{ inputs.audience }}
    - name: Install extension
      run: |
        az extension add -n ml -y
      shell: bash
    - name: Update extension
      run: |
        az extension update -n ml
      shell: bash
    - name: Allocate traffic
      run: |
        az ml online-endpoint update --name ${{ inputs.endpoint_name }} --traffic "${{ inputs.traffic_allocation }}" \
        --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }}
      shell: bash
