---

name: "Create Deployment Composite Action"

inputs:
  deployment_file:
    required: true
    type: string
  resource_group:
    required: true
    type: string
  workspace_name:
    required: true
    type: string
  endpoint_name:
    required: true
    type: string
  endpoint_type:
    required: true
    type: string
  deployment_name:
    required: true
    type: string
  deployment_type:
    required: true
    type: string
  creds:
    required: true
    

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Az login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.creds }}

    - name: Install Azure ML extensio
      run: |
        az extension add -n ml -y
      shell: bash

    - name: Update Azure ML extension
      run: |
        az extension update -n ml
      shell: bash

    - name: Create deployment
      run: |
        az ml ${{ inputs.deployment_type }} create --name ${{ inputs.deployment_name }} --endpoint ${{ inputs.endpoint_name }} \
        -f ${{ github.workspace }}/${{ inputs.deployment_file }} --resource-group ${{ inputs.resource_group }} \
        --workspace-name ${{ inputs.workspace_name }}
      shell: bash
