name: deploy-batch-endpoint-pipeline

on: 
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-yo5-d23dev'
      aml_workspace:
        description: 'AML workspace name'
        required: true
        default: 'mlw-yo5-d23dev'
      cluster_name:
        description: 'AML Batch Compute cluster name'
        required: true
        default: 'batch-cluster'    
      deployment_file:
        description: 'Deployment file'
        required: true
        default: 'mlops/azureml/deploy/batch/model1-batch-deployment.yml'
      endpoint_file:
        description: 'Endpoint file'
        required: true
        default: 'mlops/azureml/deploy/batch/model1-batch-endpoint.yml'
      endpoint_name:
        description: 'Endpoint name'
        required: true
        default: 'model1-batch'
      endpoint_type:
        description: 'Endpoint type'
        required: true
        default: 'batch'
      deployment_name:
        description: 'Deployment name'
        required: true
        default: 'model1-batch'
  repository_dispatch:
    types: [trigger_batch_endpoint]  

env:
  endpoint_type: 'batch-endpoint'
  deployment_type: 'batch-deployment'
  node_sku: Standard_DS3_v2
  cluster_size: 3
  audience: api://AzureADTokenExchange
        
permissions:
  id-token: write
  contents: read
  
jobs:

  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create Compute
        uses: ./.github/actions/create-compute
        with:
          resource_group: ${{ inputs.resource_group }}
          workspace_name: ${{ inputs.aml_workspace }} 
          compute_name: ${{ inputs.cluster_name }} 
          cluster_size: $cluster_size
          node_sku: $node_sku
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION }}  
          audience: ${{ env.audience }}
          # creds: ${{ secrets.AZURE_CREDENTIALS }}
  create-endpoint:
    runs-on: ubuntu-latest
    needs: create-compute
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2      
      - name: Create Endpoint
        uses: ./.github/actions/create-endpoint
        with:
          endpoint_file: ${{ inputs.endpoint_file }}          
          resource_group: ${{ inputs.resource_group }}
          workspace_name: ${{ inputs.aml_workspace }}
          endpoint_name: ${{ inputs.endpoint_name }}
          endpoint_type: $endpoint_type
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION }}  
          audience: ${{ env.audience }}
          # creds: ${{ secrets.AZURE_CREDENTIALS }}
  create-deployment:
    runs-on: ubuntu-latest
    needs: create-endpoint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute create-deployment composite action
        uses: ./.github/actions/create-deployment
        with:
          deployment_file: ${{ inputs.deployment_file }}
          resource_group: ${{ inputs.resource_group }}
          workspace_name: ${{ inputs.aml_workspace }}
          endpoint_name: ${{ inputs.endpoint_name }}
          deployment_name: ${{ inputs.deployment_name }}
          endpoint_type: $endpoint_type       
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION }}  
          audience: ${{ env.audience }}
          # creds: ${{ secrets.AZURE_CREDENTIALS }}
