name: deploy-model-training-pipeline

on: 
  workflow_dispatch:
    inputs:
      location:
        description: "The resource group to use"
        default: 'northeurope'
        type: string
jobs:
  register-environment:
      uses: ./.github/workflows/register-environment.yml
      with:
            environment_file: ./mlops/azureml/train/train-env.yml
            conda_file: ./data-science/environment/train-conda.yml
            resource_group: ${{ inputs.location }}
            workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
