name: deploy-model-training-pipeline


on: 
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-yo5-d23dev'
      aml_workspace:
        description: 'AML workspace name'
        required: true
        default: 'mlw-yo5-d23dev'
      cluster_name:
        description: 'AML compute cluster name'
        required: true
        default: 'cpu-cluster'
      environment_file:
        description: 'Environment file'
        required: true
        default: './data-science/models/model-1/environment/model1-train-env.yml'
      node_sku:
        description: 'Node SKU'
        required: true
        default: 'Standard_DS3_v2'
      cluster_size:
        description: 'Cluster size'
        required: true
        default: '4'
      parameters:
        description: 'Parameters file'
        required: true
        default: './mlops/azureml/train/model1-pipeline.yml'
  repository_dispatch:
    types: [trigger_model_train]  

env:
  audience: api://AzureADTokenExchange 

permissions:
  id-token: write
  contents: read
  

jobs:

  register-environment:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Register Environment
          uses: ./.github/actions/register-environment
          with:
            environment_file: ${{ inputs.environment_file }}
            resource_group: ${{ inputs.resource_group }}
            workspace_name: ${{ inputs.aml_workspace }}
            azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
            azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
            azure_subscription: ${{ secrets.AZURE_SUBSCRIPTION }}  
            audience: ${{ env.audience }}
            # creds: ${{ secrets.AZURE_CREDENTIALS }}
  create-compute:
    runs-on: ubuntu-latest
    needs: register-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create Compute
        uses: ./.github/actions/create-compute
        with:
          resource_group: ${{ inputs.resource_group }}
          workspace_name: ${{ inputs.aml_workspace }} 
          compute_name: ${{ inputs.cluster_name }} 
          cluster_size: ${{ inputs.cluster_size }}
          node_sku: ${{ inputs.node_sku }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription: ${{ secrets.AZURE_SUBSCRIPTION }}  
          audience: ${{ env.audience }}
          # creds: ${{ secrets.AZURE_CREDENTIALS }}
  run-pipeline:
    runs-on: ubuntu-latest
    needs: [register-environment, create-compute]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Pipeline
        uses: ./.github/actions/run-pipeline
        with:
          resource_group: ${{ inputs.resource_group }}
          workspace_name: ${{ inputs.aml_workspace }} 
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription: ${{ secrets.AZURE_SUBSCRIPTION }}  
          audience: ${{ env.audience }}
          # creds: ${{ secrets.AZURE_CREDENTIALS }}
          parameters: ${{ inputs.parameters }}

