name: deploy-model-training-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: ./.github/workflows/variables.yml
  register-environment:
      needs: get-config
      uses: ./.github/workflows/register-environment.yml
      with:
            environment_file: ./mlops/azureml/train/train-env.yml
            conda_file: ./data-science/environment/train-conda.yml
            resource_group: ${{ needs.get-config.outputs.resource_group }}
            workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
            creds: ${{ secrets.AZURE_CREDENTIALS }}
