name: Online Endpoint Deployment - Workflow

on: 
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-ydamlv12-yd202304dev'
      aml_workspace:
        description: 'AML workspace name'
        required: true
        default: 'mlw-ydamlv12-yd202304dev'
      deployment_file:
        description: 'Deployment file'
        required: true
        default: 'mlops/azureml/deploy/online/model1-online-deployment.yml'
      endpoint_file:
        description: 'Endpoint file'
        required: true
        default: 'mlops/azureml/deploy/online/model1-online-endpoint.yml'
      endpoint_name:
        description: 'Endpoint name'
        required: true
        default: 'taxi-gha-online'
      traffic_percentile:
        description: 'Traffic percentile'
        required: true
        default: '100'
      deployment_name:
        description: 'Deployment name'
        required: true
        default: 'taxi-gha-online'
env:
  endpoint_type: 'online-endpoint'
  deployment_type: 'online-deployment'

jobs:

  deploy-online-endpoint:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2      
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install az ml
        run: |
          az extension add -n ml
          az extension update --name ml
        shell: bash    
      - name: Create endpoint
        run: |
          az ml $endpoint_type create --name ${{ inputs.endpoint_name }} \
          -f ${{ github.workspace }}/${{ inputs.endpoint_file }} --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.aml_workspace }}
        shell: bash
      - name: Create deployment
        run: |
          az ml $deployment_type create --name ${{ inputs.deployment_name }} --endpoint ${{ inputs.endpoint_name }} \
          -f ${{ github.workspace }}/${{ inputs.deployment_file }} --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.aml_workspace }}
        shell: bash
      - name: Allocate traffic
        run: |
          az ml online-endpoint update --name ${{ inputs.endpoint_name }} --traffic "${{ inputs.deployment_name }}=${{ inputs.traffic_percentile }}"  \
          --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.aml_workspace }}
        shell: bash


